name: retroachievements_organizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.5.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.0  # For simple data storage
  http: ^1.1.0  # For API calls (will be useful for RetroAchievements API)
  path_provider: ^2.1.1 # For accessing the device's file system
  crypto: ^3.0.6
  file_picker: ^10.0.0
  url_launcher: ^6.3.1
  url_launcher_windows: ^3.1.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
